### ISSUE TITLE
OpenSSL 1.1 has introduced breaking changes

### ISSUE THREAD

**Issue by colin-streicher** [jbfavre/xca#2]
configure: The Versions of the used libraries are:
configure: Header:
configure: 	OpenSSL 1.1.0f  25 May 2017 0x1010006fL
configure: 	QT: 5.8.0
configure: Libraries:
configure: 	OpenSSL 1.1.0f  25 May 2017
configure: 	QT: 5.8.0

Then the compilation shows this. There are quite a few more like this, but all of what I've seen seem to reference the same cert struct that doesn't seem to exist anymore. My C++ is rudimentary at best, but I am going to see if I can fix it, I suspect it can be done far faster by someone who knows C++ though. 

pki_x509.cpp:190:18: error: invalid use of incomplete type ‘X509 {aka struct x509_st}’
     (char*)cert->cert_info,digest,&len))
                  ^~~~~~~~~
In file included from /usr/include/openssl/x509.h:20:0,
                 from pki_x509.h:12,
                 from pki_x509.cpp:9:
/usr/include/openssl/ossl_typ.h:119:16: note: forward declaration of ‘X509 {aka struct x509_st}’
 typedef struct x509_st X509;
                ^~~~~~~
pki_x509.cpp: In member function ‘virtual x509name pki_x509::getSubject() const’:
pki_x509.cpp:402:17: error: invalid use of incomplete type ‘X509 {aka struct x509_st}’
  x509name x(cert->cert_info->subject);
                 ^~

**Comment by jbfavre** [comment]
Hello,
This repository only purpose is to have a convenient way to package latest upstream version for my own Debian usage.
I'm not going to fix anything. You should have a look on upstream project at http://xca.sourceforge.net

Thanks
